const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Chao: 0},
	{Teclado: 0},
	{vida_player: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{Personagem: 0},
	{Âncora: 0},
	{Planodefundo: 0},
	{Áudio: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Botão: 0},
	{fundodomenu: 0},
	{Baradevida: 0},
	{Projétil: 0},
	{Munição: 0},
	{vida_zumbi: 0},
	{zombi: 0},
	{Sensor_Pulo: 0},
	{morte: 0},
	{GameOuver: 0},
	{BotãoGameOuver: 0},
	{Telafundoultimcidade: 0},
	{Sprite3: 0},
	{SensorSaida: 0},
	{Sprite: 0},
	{Sensorsom: 0},
	{Vida: 0},
	{podeAtirar: 0},
	{DirecaoBala: 0},
	{SomParaTocar: 0}
];

self.InstanceType = {
	Chao: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Personagem: class extends self.ISpriteInstance {},
	Planodefundo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Botão: class extends self.ISpriteInstance {},
	fundodomenu: class extends self.ISpriteInstance {},
	Baradevida: class extends self.ISpriteInstance {},
	Munição: class extends self.ISpriteInstance {},
	zombi: class extends self.ISpriteInstance {},
	Sensor_Pulo: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	GameOuver: class extends self.ISpriteInstance {},
	BotãoGameOuver: class extends self.ISpriteInstance {},
	Telafundoultimcidade: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SensorSaida: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sensorsom: class extends self.ISpriteInstance {}
}